routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', "LoginController@index")->name('login');
Route::post('login', "LoginController@doLogin")->name('doLogin');
Route::get('register', "LoginController@register")->name('register');
Route::post('register', "LoginController@doRegister")->name('doRegister');
Route::get('logout', "LoginController@logout")->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

    Route::get('myTests', 'TesteController@showMyTests')->name('myTests');
    Route::resource('teste', 'TesteController', [ 'except' => [ 'show' ] ]);
    Route::resource('teste.questao', 'QuestaoController', [ 'except' => [ 'index', 'show' ]]);
    Route::get('responder/{teste}', "QuestaoRespostaController@create")->name('responseTest');
    Route::post('responder/{teste}', "QuestaoRespostaController@store")->name('storeResponseTest');
    Route::get('result/{teste}', "QuestaoRespostaController@showResult")->name('testResult');
});

app/Http/Controllers/QuestaoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Questao;
use App\Model\Teste;


class QuestaoController extends Controller
{
    const alternativas = ['A', 'B', 'C', 'D', 'E'];
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($testeId)
    {
        $teste = Teste::findOrFail($testeId);
        return view('pages.questao.create')->with('teste', $teste)->with('alternativas', self::alternativas);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store($testeId, Request $request)
    {
        $teste = Teste::findOrFail($testeId);
        $data = $request->all();

        Questao::create($data);
        return redirect()->route('teste.edit', $teste->id)->with('success', 'Questão adicionada com sucesso.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($testeId, $id)
    {
        $teste = Teste::findOrFail($testeId);
        $questao = Questao::findOrFail($id);
        return view('pages.questao.edit')->with('teste', $teste->id)->with('questao', $questao)->with('alternativas', self::alternativas);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($testeId, $id, Request $request)
    {
        $teste = Teste::findOrFail($testeId);
        $questao = Questao::findOrFail($id);

        $data = $request->all();
        $questao->update($data);
        return redirect()->route('teste.edit', $teste->id)->with('success', 'Questão alterada com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($testeId, $id)
    {
        $teste = Teste::findOrFail($testeId);
        $questao = Questao::findOrFail($id);
        $questao->delete();
        return redirect()->route('teste.edit', $teste->id)->with('success', 'Questão removida com sucesso.');
    }
}

resources/views/pages/questao/create.blade.php
@extends('layouts.default')
@section('pageName', 'Questão - Criar')
@section('content')
<form action="{{route('teste.questao.store', $teste->id)}}" method="POST">
    @csrf

    <input type="hidden" name="id_teste" value="{{ $teste->id }}">
    <div class="form-group">
        <label for="enunciado">Enunciado</label>
        <input class="form-control" name="enunciado" id="enunciado" value="{{old('enunciado')}}">
    </div>
    @foreach($alternativas as $a)
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="resposta{{ $a }}">{{ $a }}</span>
            </div>
            <input type="text" class="form-control" name="resposta{{ $a }}" value="{{ old('resposta' . $a) }}">
        </div>
    @endforeach
    <div class="form-group">
        <label for="correta">Resposta</label>
        <select class="form-control" id="correta" name="correta">
            @foreach($alternativas as $a)
                <option value="{{ $a }}" {{ ( old('correta') == $a) ? 'selected' : '' }} >{{ $a }}</option>
            @endforeach
        </select>
    </div>

    <button class="btn btn-success">Inserir</button>
</form>
@stop

resources/views/pages/questao/edit.blade.php
@extends('layouts.default')
@section('pageName', 'Questão - Editar')
@section('content')
<form action="{{route('teste.questao.update', ['questao' => $questao->id, 'teste' => $questao->id_teste])}}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="enunciado">Enunciado</label>
        <input class="form-control" name="enunciado" id="enunciado" value="{{$questao->enunciado}}">
    </div>
    @foreach($alternativas as $a)
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="resposta{{ $a }}">{{ $a }}</span>
            </div>
            <input type="text" class="form-control" name="resposta{{ $a }}" value="{{ $questao->{'resposta' . $a} }}">
        </div>
    @endforeach
    <div class="form-group">
        <label for="correta">Resposta</label>
        <select class="form-control" id="correta" name="correta">
            @foreach($alternativas as $a)
                <option value="{{ $a }}" {{ ( $questao->correta == $a) ? 'selected' : '' }} >{{ ($a . ' - ' . $questao->{'resposta' . $a}) }}</option>
            @endforeach
        </select>
    </div>

    <button class="btn btn-success">Atualizar</button>
    <button form="formDelete" class="btn btn-danger">Remover</button>
</form>

<form id="formDelete" action="{{route('teste.questao.destroy', ['questao' => $questao->id, 'teste' => $questao->id_teste])}}" method="POST">
    @csrf
    @method('DELETE')
</form>
@stop