routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', "LoginController@index")->name('login');
Route::post('login', "LoginController@doLogin")->name('doLogin');
Route::get('register', "LoginController@register")->name('register');
Route::post('register', "LoginController@doRegister")->name('doRegister');
Route::get('logout', "LoginController@logout")->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

    Route::get('myTests', 'TesteController@showMyTests')->name('myTests');
    Route::resource('teste', 'TesteController', [ 'except' => [ 'show' ] ]);
    Route::resource('teste.questao', 'QuestaoController', [ 'except' => [ 'index', 'show' ]]);
    Route::get('responder/{teste}', "QuestaoRespostaController@create")->name('responseTest');
    Route::post('responder/{teste}', "QuestaoRespostaController@store")->name('storeResponseTest');
    Route::get('result/{teste}', "QuestaoRespostaController@showResult")->name('testResult');
});

app/Http/Controllers/TesteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Model\Teste;
use Illuminate\Support\Facades\Auth;

class TesteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $testes = Teste::all();
        $testes->load('owner');

        return view('pages.teste.index')->with('testes', $testes);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function showMyTests()
    {
        $user = Auth::user();
        $testes = $user->tests;
        $testes->load('owner');

        return view('pages.teste.index')->with('testes', $testes);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.teste.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = Auth::user();
        $data = $request->all();
        $data['id_usuario'] = $user->id;

        Teste::create($data);
        return redirect()->route('teste.index')->with('success', 'Teste inserido com sucesso');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teste = Teste::findOrFail($id);
        $teste->load('questions');

        return view('pages.teste.edit')->withTeste($teste);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $user = Auth::user();
        $teste = Teste::findOrFail($id);
        if($teste->owner != $user) {
            return redirect()->route('teste.index')->with('errorMessage', 'Teste não pode ser modificado, pois não é de sua autoria.');
        }

        $teste->update($data);
        return redirect()->route('teste.index')->with('success', 'Teste atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
        $teste = Teste::findOrFail($id);
        if($teste->owner != $user) {
            return redirect()->route('teste.index')->with('errorMessage', 'Teste não pode ser excluido, pois não é de sua autoria.');
        }

        $teste->delete();
        return redirect()->route('teste.index')->with('success', 'Teste removido com sucesso.');
    }
}

resources/views/pages/teste/create.blade.php
@extends('layouts.default')
@section('pageName', 'Teste - Criar')
@section('content')
<form action="{{route('teste.store')}}" method="post">
    @csrf
    <div class="form-group">
        <label for="nome">Nome</label>
        <input class="form-control" name="nome" id="nome" value="{{old('nome')}}" required>
    </div>
    <div class="form-group">
        <label for="pontuacaoMinima">Pontuação Minima</label>
        <input class="form-control" name="pontuacao_minima" id="pontuacaoMinima" value="{{old('pontuacao_minima')}}" required>
    </div>
    <div class="form-group">
        <label for="pontuacaoMaxima">Pontuação Máxima</label>
        <input class="form-control" name="pontuacao_maxima" id="pontuacaoMaxima" value="{{old('pontuacao_maxima')}}" required>
    </div>

    <button class="btn btn-lg btn-success">Inserir</button>
</form>
@stop

resources/views/pages/teste/edit.blade.php
@extends('layouts.default')
@section('pageName', 'Teste - Editar')
@section('content')
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Atenção</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Deseja remover esta pergunta?
            </div>
            <div class="modal-footer">
                <form id="formDeletePergunta" action="" method="POST">
                    @csrf
                    @method('DELETE')

                    <button type="button" class="btn btn-success" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-danger">Remover</button>
                </form>
            </div>
        </div>
    </div>
</div>
<form action="{{route( 'teste.update', $teste->id ) }}" method="POST">
    @csrf
    @method('PUT')
    <div class="form-group">
        <label for="nome">Nome</label>
        <input class="form-control" name="nome" id="nome" value="{{ $teste->nome }}">
    </div>
    <div class="form-group">
        <label for="pontuacaoMinima">Pontuação Minima</label>
        <input class="form-control" name="pontuacao_minima" id="pontuacaoMinima" value="{{ $teste->pontuacao_minima }}" required>
    </div>
    <div class="form-group">
        <label for="pontuacaoMaxima">Pontuação Máxima</label>
        <input class="form-control" name="pontuacao_maxima" id="pontuacaoMaxima" value="{{ $teste->pontuacao_maxima }}">
    </div>
    <table class="table">
        <thead>
            <tr>
                <td colspan="2">
                    <a class="btn btn-success float-right text-white" role="button" href="{{ route('teste.questao.create', [ "teste" => $teste->id ]) }}">
                        <i class="fa fa-plus" aria-hidden="true"></i> Novo
                    </a>
                </td>
            </tr>
            <tr>
                <th scope="col">Pergunta</th>
                <th scope="col" class="text-center">Actions</th>
            </tr>
        </thead>
        <tbody>
        @forelse($teste->questions as $questao)
            <tr>
                <td>{{ $questao->enunciado }} </td>
                <td class="text-center">
                    <div class="list-icons">
                        <div class="dropdown">
                            <a href="#" class="list-icons-item" data-toggle="dropdown">
                                <i class="icon-menu9"></i>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right">
                                <a href="{{ route('teste.questao.edit', [ "questao" => $questao->id, "teste" => $teste->id ]) }}" class="dropdown-item"><i class="icon-database-edit2"></i> Editar questão</a>
                                <a class="dropdown-item deleteButton" data-toggle="modal" data-target="#deleteModal" data-endpoint="{{ route('teste.questao.destroy', [ "questao" => $questao->id, "teste" => $teste->id ]) }}">
                                    <i class="icon-trash" aria-hidden="true"></i> Remover questão
                                </a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="2">Não há perguntas cadastrados.</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    <button class="btn btn-success">Atualizar</button>
    <button form="formDelete" class="btn btn-danger">Remover</button>
</form>

<form id="formDelete" action="{{ route('teste.destroy', $teste->id) }}" method="POST">
    @csrf
    @method('DELETE')
</form>
<script>
    window.addEventListener('load', function() {
        $('.deleteButton').click(function() {
            $route = $(this).data('endpoint');
            $('#formDeletePergunta').attr('action', $route);
        });
    });
</script>
@stop

resources/views/pages/teste/index.blade.php
@extends('layouts.default')
@section('pageName', 'Teste - Listar')
@section('content')
    <table class="table">
        <thead>
        <tr>
            <th scope="col" class="text-center">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Autor</th>
            <th scope="col" class="text-center">Actions</th>
        </tr>
        </thead>
        <tbody>
        @forelse($testes as $teste)
            <tr>
                <th scope="row" class="text-center">{{ $teste->id }}</th>
                <td> {{ $teste->nome }}</td>
                <td> {{ $teste->owner->nome }}</td>
                <td class="text-center">
                    <div class="list-icons">
                        <div class="dropdown">
                            <a href="#" class="list-icons-item" data-toggle="dropdown">
                                <i class="icon-menu9"></i>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right">
                                @if(Auth::user()->id == $teste->owner->id)
                                    <a href="{{ route('teste.edit', $teste->id) }}" class="dropdown-item"><i class="icon-database-edit2"></i> Editar teste</a>
                                @endif
                                <a href="{{ route('responseTest', $teste->id) }}" class="dropdown-item"><i class="icon-bubble-dots4"></i> Responder teste</a>
                            </div>
                        </div>
                    </div>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="4">Não há testes cadastrados.</td>
            </tr>
        @endforelse
        </tbody>
    </table>
    <div class="row">
        <div class="col-12 text-center">
            <a class="btn btn-success" href="{{ route('teste.create') }}" role="button">Inserir teste</a>
        </div>
    </div>

@endsection