routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('login', "LoginController@index")->name('login');
Route::post('login', "LoginController@doLogin")->name('doLogin');
Route::get('register', "LoginController@register")->name('register');
Route::post('register', "LoginController@doRegister")->name('doRegister');
Route::get('logout', "LoginController@logout")->name('logout');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'HomeController@index')->name('home')->middleware('auth');

    Route::get('myTests', 'TesteController@showMyTests')->name('myTests');
    Route::resource('teste', 'TesteController', [ 'except' => [ 'show' ] ]);
    Route::resource('teste.questao', 'QuestaoController', [ 'except' => [ 'index', 'show' ]]);
    Route::get('responder/{teste}', "QuestaoRespostaController@create")->name('responseTest');
    Route::post('responder/{teste}', "QuestaoRespostaController@store")->name('storeResponseTest');
    Route::get('result/{teste}', "QuestaoRespostaController@showResult")->name('testResult');
});

resources/views/includes/footer.blade.php
<div class="navbar navbar-expand-lg navbar-light">
    <div class="text-center d-lg-none w-100">
        <button type="button" class="navbar-toggler dropdown-toggle" data-toggle="collapse" data-target="#navbar-footer">
            <i class="icon-unfold mr-2"></i>
            footer
        </button>
    </div>

    <div class="navbar-collapse collapse" id="navbar-footer">
                <span class="navbar-text">
                    © Copyright 2020 Mateus & Dalvo
                </span>
    </div>
</div>

resources/views/includes/head.blade.php
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>@yield('pageName')</title>

<!-- global stylesheets -->
<link href="https://fonts.googleapis.com/css?family=roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/icons/icomoon/styles.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/bootstrap_limitless.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/layout.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/components.min.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('assets/css/colors.min.css') }}" rel="stylesheet" type="text/css">
<!-- /global stylesheets -->

<!-- core js files -->
<script src="{{ asset('assets/js/main/jquery.min.js') }}"></script>
<script src="{{ asset('assets/js/main/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/loaders/blockui.min.js') }}"></script>
<!-- /core js files -->

<!-- theme js files -->
<script src="{{ asset('assets/js/plugins/forms/styling/uniform.min.js') }}"></script>

<script src="{{ asset('assets/js/app.js') }}"></script>
<script src="{{ asset('assets/js/plugins/tables/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/visualization/d3/d3.min.js') }}"></script>
<script src="{{ asset('assets/js/plugins/visualization/d3/d3_tooltip.js') }}"></script>


<!-- /theme js files -->

resources/views/includes/header.blade.php
<div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
        <div class="page-title d-flex">
            <h4><i onclick="javascript:history.back()" class="icon-arrow-left52 mr-2"></i><span class="font-weight-semibold"> @yield('pageName') </span></h4>
            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>

resources/views/includes/navbar.blade.php
<div class="navbar navbar-expand-md navbar-dark">
    <div class="navbar-brand">
        <a href="{{ route('home') }}" class="d-inline-block">
            <img src="{{ asset('assets/images/logo_light.png') }}" alt="">
        </a>
    </div>

    <div class="d-md-none">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile">
            <i class="icon-tree5"></i>
        </button>
        <button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
            <i class="icon-paragraph-justify3"></i>
        </button>
    </div>

    <div class="collapse navbar-collapse" id="navbar-mobile">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="#" class="navbar-nav-link sidebar-control sidebar-main-toggle d-none d-md-block">
                    <i class="icon-paragraph-justify3"></i>
                </a>
            </li>
        </ul>

        <span class="ml-md-3 mr-md-auto"></span>

        <ul class="navbar-nav">
            <li class="nav-item dropdown dropdown-user">
                <a href="#" class="navbar-nav-link d-flex align-items-center dropdown-toggle" data-toggle="dropdown">
                    <img src="{{ asset('assets/images/placeholders/placeholder.jpg') }}" class="rounded-circle mr-2" height="34" alt="">
                    <span>{{ Auth::user()->nome }}</span>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                    <a href="{{ route('myTests') }}" class="dropdown-item"><i class="icon-stack"></i> Meus testes</a>
                    <a href="{{ route('logout') }}" class="dropdown-item"><i class="icon-switch2"></i> Sair</a>
                </div>
            </li>
        </ul>
    </div>
</div>

resources/views/includes/sidebar.blade.php
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">

    <!-- sidebar mobile toggler -->
    <div class="sidebar-mobile-toggler text-center">
        <a href="#" class="sidebar-mobile-main-toggle">
            <i class="icon-arrow-left8"></i>
        </a>
        navigation
        <a href="#" class="sidebar-mobile-expand">
            <i class="icon-screen-full"></i>
            <i class="icon-screen-normal"></i>
        </a>
    </div>
    <!-- /sidebar mobile toggler -->


    <!-- sidebar content -->
    <div class="sidebar-content">

        <!-- user menu -->
        <div class="sidebar-user">
            <div class="card-body">
                <div class="media">
                    <div class="mr-3">
                        <a href="javascript:void(0)"><img src="{{ asset('assets/images/placeholders/placeholder.jpg') }}" width="38" height="38" class="rounded-circle" alt=""></a>
                    </div>

                    <div class="media-body">
                        <div class="media-title font-weight-semibold">{{ Auth::user()->nome }}</div>
                        <div class="font-size-xs opacity-50">
                            <i class="icon-pin font-size-sm"></i>
                        </div>
                    </div>

                    <div class="ml-3 align-self-center">
                        <a href="javascript:void(0)" class="text-white"><i class="icon-cog3"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /user menu -->


        <!-- main navigation -->
        <div class="card card-sidebar-mobile">
            <ul class="nav nav-sidebar" data-nav-type="accordion">

                <!-- main -->
                <li class="nav-item-header"><div class="text-uppercase font-size-xs line-height-xs">main</div> <i class="icon-menu" title="main"></i></li>
                <li class="nav-item">
                    <a href="{{ route('home') }}" class="nav-link">
                        <i class="icon-home4"></i>
                        <span>Home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('teste.index') }}" class="nav-link">
                        <i class="icon-stack"></i>
                        <span>Testes</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- /main navigation -->

    </div>
    <!-- /sidebar content -->
</div>